# Generated by Django 5.2.8 on 2025-11-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesempenhoPainelSolar',
            fields=[
                ('painel_solar_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hora', models.IntegerField()),
                ('radiacao_wm2', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('potencia_km', models.FloatField()),
            ],
        ),
    ]
