# Generated by Django 5.2.8 on 2025-11-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiscoCardiacoPaciente',
            fields=[
                ('paciente_id', models.IntegerField(primary_key=True, serialize=False)),
                ('idade', models.IntegerField()),
                ('colesterol', models.IntegerField()),
                ('pressao', models.IntegerField()),
                ('risco', models.IntegerField()),
            ],
        ),
    ]
